param(
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$appRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$envFile = Join-Path $appRoot ".env.local"

function Read-Value {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name,
        [string]$CurrentValue = "",
        [string]$DefaultValue = "",
        [switch]$AsSecret
    )

    $displayDefault = if ($CurrentValue) { $CurrentValue } else { $DefaultValue }
    if ($AsSecret) {
        if ($displayDefault) {
            Write-Host "$Name [current value exists]" -ForegroundColor Yellow
        } else {
            Write-Host "$Name" -ForegroundColor Yellow
        }
        $secure = Read-Host "Enter value" -AsSecureString
        $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
        try {
            $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
        } finally {
            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
        }
        if ([string]::IsNullOrWhiteSpace($plain)) {
            if ($CurrentValue) { return $CurrentValue }
            return $DefaultValue
        }
        return $plain
    }

    if ($displayDefault) {
        $entered = Read-Host "$Name [$displayDefault]"
    } else {
        $entered = Read-Host "$Name"
    }

    if ([string]::IsNullOrWhiteSpace($entered)) {
        if ($CurrentValue) { return $CurrentValue }
        return $DefaultValue
    }

    return $entered.Trim()
}

function Parse-EnvFile {
    param(
        [string]$Path
    )
    $result = @{}
    if (-not (Test-Path -LiteralPath $Path)) {
        return $result
    }

    Get-Content -LiteralPath $Path | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) {
            return
        }
        $parts = $line.Split("=", 2)
        if ($parts.Length -ne 2) {
            return
        }
        $key = $parts[0].Trim()
        $value = $parts[1].Trim()
        $result[$key] = $value
    }

    return $result
}

Write-Host ""
Write-Host "MMM local environment setup" -ForegroundColor Cyan
Write-Host "Target file: $envFile" -ForegroundColor Cyan
Write-Host ""

if ((Test-Path -LiteralPath $envFile) -and -not $Force) {
    $overwrite = Read-Host ".env.local already exists. Update it now? (y/N)"
    if ($overwrite -notin @("y", "Y", "yes", "YES")) {
        Write-Host "No changes made." -ForegroundColor Yellow
        exit 0
    }
}

$existing = Parse-EnvFile -Path $envFile

$supabaseUrl = Read-Value `
    -Name "VITE_SUPABASE_URL" `
    -CurrentValue ($existing["VITE_SUPABASE_URL"]) `
    -DefaultValue ""

$supabaseAnon = Read-Value `
    -Name "VITE_SUPABASE_ANON_KEY" `
    -CurrentValue ($existing["VITE_SUPABASE_ANON_KEY"]) `
    -DefaultValue "" `
    -AsSecret

$appUrl = Read-Value `
    -Name "VITE_APP_URL" `
    -CurrentValue ($existing["VITE_APP_URL"]) `
    -DefaultValue "http://127.0.0.1:4173"

if ([string]::IsNullOrWhiteSpace($supabaseUrl) -or [string]::IsNullOrWhiteSpace($supabaseAnon)) {
    Write-Host ""
    Write-Host "VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are required." -ForegroundColor Red
    Write-Host "Aborting without writing .env.local." -ForegroundColor Red
    exit 1
}

$content = @(
    "# Auto-generated by scripts/setup-local-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
    "VITE_SUPABASE_URL=$supabaseUrl"
    "VITE_SUPABASE_ANON_KEY=$supabaseAnon"
    "VITE_APP_URL=$appUrl"
)

[System.IO.File]::WriteAllLines($envFile, $content, [System.Text.UTF8Encoding]::new($false))

Write-Host ""
Write-Host "Saved: $envFile" -ForegroundColor Green
Write-Host ""
Write-Host "Next step:" -ForegroundColor Cyan
Write-Host "  pnpm dev" -ForegroundColor White
