/**
 * @maturion/ai-centre — Feedback Pipeline Type Definitions
 *
 * Wave 9.2 — AI Feedback Pipeline (Self-Learning Loop Migration to AIMC)
 *
 * Canonical TypeScript types for the AI feedback pipeline, including:
 *   - FeedbackEvent   — row shape for ai_feedback_events table
 *   - ARCReviewStatus — ARC approval gate status values
 *   - FeedbackType    — permitted feedback classification values
 *   - FeedbackPipelineInterface — service contract for submit/review operations
 *
 * These interfaces are NORMATIVE. Implementations in Wave 9.4 MUST match
 * signatures exactly. This file MUST NOT be modified without CS2 approval.
 *
 * References:
 *   ARCH_FREEZE-wave9-self-learning-loop-20260226.md §4.1 (schema)
 *   Issue #613 — Wave 9.2 authority: CS2 (@APGI-cmy)
 *   GRS-011 | APS §10 | AAD §10.1
 */

// ---------------------------------------------------------------------------
// ARC (Adaptive Review Committee) review status
// ---------------------------------------------------------------------------

/**
 * ARC review gate status for a feedback event.
 *
 * - `pending`  — submitted but not yet reviewed by the ARC process
 * - `approved` — ARC has approved the feedback for knowledge base promotion
 * - `rejected` — ARC has rejected the feedback (not suitable for promotion)
 */
export type ARCReviewStatus = 'pending' | 'approved' | 'rejected';

// ---------------------------------------------------------------------------
// Feedback classification
// ---------------------------------------------------------------------------

/**
 * Classification of a user feedback event.
 *
 * - `positive`   — user found the AI response helpful/correct
 * - `negative`   — user found the AI response unhelpful/incorrect
 * - `correction` — user provides a corrected version of the AI response
 * - `flag`       — user flags the response for ARC review (e.g. policy concern)
 */
export type FeedbackType = 'positive' | 'negative' | 'correction' | 'flag';

// ---------------------------------------------------------------------------
// FeedbackEvent — row shape for ai_feedback_events
// ---------------------------------------------------------------------------

/**
 * Represents a single feedback event submitted by a user for an AI interaction.
 *
 * Mirrors the `ai_feedback_events` table schema defined in
 * `supabase/migrations/005_ai_feedback_pipeline.sql`.
 */
export interface FeedbackEvent {
  /** UUID primary key (generated by database). Absent on create. */
  id?: string;

  /** Organisation the feedback belongs to (tenant isolation). */
  organisationId: string;

  /** Session identifier linking this feedback to its originating AI session. */
  sessionId: string;

  /** Authenticated user who submitted the feedback. Nullable (anonymous allowed). */
  userId?: string;

  /** Unique identifier for the specific AI interaction being rated. */
  interactionId: string;

  /** Classification of the feedback. */
  feedbackType: FeedbackType;

  /**
   * Optional numeric rating (1–5 scale).
   * Required when feedbackType is 'positive' or 'negative'; optional otherwise.
   */
  rating?: number;

  /** Free-text comment from the user. Optional. */
  comment?: string;

  /**
   * User-supplied correction text.
   * Required when feedbackType is 'correction'; optional otherwise.
   */
  correctionText?: string;

  /** AIMC capability that produced the interaction being reviewed. */
  capability: string;

  /** ID of the agent that handled the interaction. */
  agentId: string;

  /**
   * ARC review gate status. Defaults to `'pending'` on insert.
   * Only updatable by service_role (ARC-gated endpoint).
   */
  arcStatus?: ARCReviewStatus;

  /** Identity of the ARC reviewer who approved or rejected this event. */
  arcReviewedBy?: string;

  /** Timestamp when the ARC review was completed. */
  arcReviewedAt?: Date;

  /** Optional notes from the ARC reviewer. */
  arcNotes?: string;

  /** Timestamp when the feedback event was created (database-generated). */
  createdAt?: Date;
}

// ---------------------------------------------------------------------------
// FeedbackPipelineInterface — service contract (implemented in Wave 9.4)
// ---------------------------------------------------------------------------

/**
 * Service contract for the AI Feedback Pipeline.
 *
 * Implementations live in `packages/ai-centre/src/feedback/FeedbackPipeline.ts`
 * (Wave 9.4). This interface is defined here (Wave 9.2) so that Wave 9.4
 * can import and implement it without circular dependency.
 *
 * All methods route exclusively through AIMC — no legacy table access permitted.
 */
export interface FeedbackPipelineInterface {
  /**
   * Submit a new feedback event.
   *
   * Writes to `ai_feedback_events` with `arc_status = 'pending'`.
   * Requires an authenticated user context with a valid `organisationId`.
   *
   * @param event  Feedback payload (excludes server-generated id, arcStatus, createdAt).
   * @returns      The persisted FeedbackEvent with id, arcStatus='pending', createdAt.
   * @throws       AIMCBypassError if organisationId is missing or invalid.
   */
  submit(event: Omit<FeedbackEvent, 'id' | 'arcStatus' | 'createdAt'>): Promise<FeedbackEvent>;

  /**
   * List all pending feedback events for an organisation.
   *
   * Returns only events with `arc_status = 'pending'`, ordered by `created_at` ascending.
   * Requires service_role or Lead Auditor context.
   *
   * @param organisationId  The organisation to query.
   * @returns               Array of pending FeedbackEvents.
   */
  listPending(organisationId: string): Promise<FeedbackEvent[]>;

  /**
   * Approve a pending feedback event (ARC gate).
   *
   * Sets `arc_status = 'approved'`, records `arc_reviewed_by`, `arc_reviewed_at`,
   * and optional `arc_notes`. Requires service_role token.
   *
   * @param id          UUID of the FeedbackEvent to approve.
   * @param reviewedBy  Identity of the ARC reviewer.
   * @param notes       Optional reviewer notes.
   * @returns           The updated FeedbackEvent with arcStatus='approved'.
   */
  approve(id: string, reviewedBy: string, notes?: string): Promise<FeedbackEvent>;

  /**
   * Reject a pending feedback event (ARC gate).
   *
   * Sets `arc_status = 'rejected'`, records `arc_reviewed_by`, `arc_reviewed_at`,
   * and optional `arc_notes`. Requires service_role token.
   *
   * @param id          UUID of the FeedbackEvent to reject.
   * @param reviewedBy  Identity of the ARC reviewer.
   * @param notes       Optional reviewer notes.
   * @returns           The updated FeedbackEvent with arcStatus='rejected'.
   */
  reject(id: string, reviewedBy: string, notes?: string): Promise<FeedbackEvent>;
}
