"""
services/parsing.py — Document Parsing service (Wave 15 implementation).

Architecture reference: modules/mat/02-architecture/system-architecture.md §4
  "Criteria Parsing Pipeline: CriteriaUpload → invoke-ai-parse-criteria →
   AI Gateway DocumentParser → DB write-back (domains, mini_performance_standards, criteria)"

FRS: FR-005 (criteria parsing pipeline), FR-103 (error surfacing)
Wave: 15 — Post-Delivery Oversight Remediation (T-W15-IMPL-001)
"""

from __future__ import annotations

import io
import logging
import os
import re
import urllib.parse
from typing import Any

import httpx
from PyPDF2 import PdfReader as PdfReader
from docx import Document as DocxDocument
from fastapi import APIRouter, HTTPException
from openai import OpenAI
from pydantic import BaseModel

logger = logging.getLogger(__name__)

router = APIRouter()

# Trusted Supabase Storage base URL — from env var only, never user-provided
SUPABASE_STORAGE_URL = os.environ.get("SUPABASE_STORAGE_URL", "").rstrip("/")

# ── LDCS document structure constants ──────────────────────────────────────────
# The LDCS (Local Delivery Compliance Standard) uses 25 MPS across multiple domains.
# Criteria are numbered in a hierarchical X.Y.Z pattern.
LDCS_NUMBERED_HIERARCHY_PATTERN = re.compile(r"\b\d+\.\d+(?:\.\d+)?\b")
LDCS_MPS_TOTAL = 25
LDCS_MARKERS = ["LDCS", "Local Delivery Compliance Standard", "mini performance standard"]

GPT_MODEL = "gpt-4-turbo"
CONFIDENCE_REVIEW_THRESHOLD = 0.75  # flag needs_human_review when below this


# ── Request / Response models ───────────────────────────────────────────────────

class ParseRequest(BaseModel):
    """
    Request model for the /parse endpoint.

    Security: document_url is a signed Supabase Storage URL generated by the Edge Function.
    The AI Gateway extracts only the path and query components from this URL and combines
    them with the trusted SUPABASE_STORAGE_URL base from the environment (SSRF mitigation).
    """
    document_url: str
    tenant_id: str
    file_path: str | None = None


class CriterionResult(BaseModel):
    mps_number: str
    number: str
    title: str
    description: str
    source_anchor: str


class MpsResult(BaseModel):
    domain_name: str
    name: str
    number: str
    sort_order: int


class DomainResult(BaseModel):
    name: str
    sort_order: int


class ParseResponse(BaseModel):
    status: str
    domains: list[DomainResult]
    mini_performance_standards: list[MpsResult]
    criteria: list[CriterionResult]
    needs_human_review: bool
    ldcs_detected: bool
    confidence_score: float
    source_anchor: str
    document_url: str
    tenant_id: str


# ── Text extraction helpers ─────────────────────────────────────────────────────

def _extract_text_from_pdf(content: bytes) -> str:
    """Extract raw text from a PDF document using PyPDF2."""
    reader = PdfReader(io.BytesIO(content))
    pages = []
    for page in reader.pages:
        text = page.extract_text()
        if text:
            pages.append(text)
    return "\n".join(pages)


def _extract_text_from_docx(content: bytes) -> str:
    """Extract raw text from a DOCX document using python-docx."""
    doc = DocxDocument(io.BytesIO(content))
    return "\n".join(para.text for para in doc.paragraphs if para.text.strip())


# SSRF mitigation: only extract path+query from the signed URL and combine
# with the trusted storage base URL from the environment.
# This ensures the scheme and hostname are never user-controlled.
def _build_safe_fetch_url(document_url: str) -> str:
    """
    Build a safe fetch URL by using the trusted SUPABASE_STORAGE_URL base
    and appending only the path and query extracted from the signed URL.

    This prevents SSRF: the scheme and hostname come from a trusted env var,
    not from the user-provided signed URL string.
    """
    parsed = urllib.parse.urlparse(document_url)
    # Only use path and query from the signed URL (never scheme or host)
    path = parsed.path.lstrip("/")
    query = f"?{parsed.query}" if parsed.query else ""
    if not SUPABASE_STORAGE_URL:
        raise ValueError("SUPABASE_STORAGE_URL environment variable is not configured")
    return f"{SUPABASE_STORAGE_URL}/{path}{query}"


def _extract_document_text(document_url: str) -> tuple[str, str]:
    """
    Download document from Supabase Storage and extract text.

    SSRF mitigation: scheme and hostname come from SUPABASE_STORAGE_URL (env var),
    not from the user-provided signed URL. Only path and query are extracted from
    the user-provided URL.

    Returns (extracted_text, format) where format is 'pdf' or 'docx'.
    """
    safe_url = _build_safe_fetch_url(document_url)
    response = httpx.get(safe_url, follow_redirects=False, timeout=30)
    response.raise_for_status()

    content_type = response.headers.get("content-type", "").lower()
    content = response.content

    if "pdf" in content_type or document_url.lower().endswith(".pdf"):
        return _extract_text_from_pdf(content), "pdf"
    elif "wordprocessingml" in content_type or document_url.lower().endswith(".docx"):
        return _extract_text_from_docx(content), "docx"
    else:
        # Attempt PDF first, then DOCX
        try:
            return _extract_text_from_pdf(content), "pdf"
        except Exception:
            return _extract_text_from_docx(content), "docx"


def _detect_ldcs_pattern(text: str) -> bool:
    """Detect whether the document text follows the LDCS numbered hierarchy."""
    has_numbered_hierarchy = bool(LDCS_NUMBERED_HIERARCHY_PATTERN.search(text))
    has_ldcs_marker = any(marker.lower() in text.lower() for marker in LDCS_MARKERS)
    return has_numbered_hierarchy or has_ldcs_marker


# ── GPT-4 Turbo structured extraction ──────────────────────────────────────────

_SYSTEM_PROMPT = """\
You are an expert compliance document analyser specialised in extracting structured audit criteria
from compliance frameworks such as the LDCS (Local Delivery Compliance Standard).

The LDCS defines {mps_count} Mini Performance Standards (MPS) organised under multiple Domains.
Criteria are identified by hierarchical numbers (e.g. "3.2.1").

Extract the full Domain → MPS → Criteria hierarchy from the document text.

Return a JSON object with this schema:
{{
  "confidence_score": <float 0.0-1.0>,
  "domains": [{{"name": "...", "sort_order": <int>}}],
  "mini_performance_standards": [
    {{"domain_name": "...", "name": "...", "number": "...", "sort_order": <int>}}
  ],
  "criteria": [
    {{
      "mps_number": "...",
      "number": "...",
      "title": "...",
      "description": "...",
      "source_anchor": "<page or section reference in source document>"
    }}
  ]
}}

source_anchor must reference the section or page number in the source document for traceability.
""".format(mps_count=LDCS_MPS_TOTAL)


def _call_gpt4_turbo(document_text: str) -> dict[str, Any]:
    """Call GPT-4 Turbo to extract structured criteria from document text."""
    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

    response = client.chat.completions.create(
        model=GPT_MODEL,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {
                "role": "user",
                "content": f"Extract the criteria hierarchy from this compliance document:\n\n{document_text[:12000]}",
            },
        ],
        response_format={"type": "json_object"},
        temperature=0.1,
    )

    import json
    return json.loads(response.choices[0].message.content or "{}")


# ── FastAPI route ───────────────────────────────────────────────────────────────

@router.post("/parse", response_model=ParseResponse)
async def parse_document(request: ParseRequest) -> ParseResponse:
    """
    Parse a compliance document and return structured Domain → MPS → Criteria hierarchy.

    Security: document_url must be a signed Supabase Storage URL; external URLs are
    rejected by the invoking Edge Function (SSRF mitigation at the Edge Function layer).
    """
    try:
        # 1. Extract document text
        document_text, _doc_format = _extract_document_text(request.document_url)

        # 2. Detect LDCS pattern
        ldcs_detected = _detect_ldcs_pattern(document_text)

        # 3. Call GPT-4 Turbo for structured extraction
        extracted = _call_gpt4_turbo(document_text)

        confidence_score: float = float(extracted.get("confidence_score", 0.5))
        needs_human_review: bool = confidence_score < CONFIDENCE_REVIEW_THRESHOLD

        # 4. Build typed response
        domains = [DomainResult(**d) for d in extracted.get("domains", [])]
        mps_list = [MpsResult(**m) for m in extracted.get("mini_performance_standards", [])]
        criteria_list = [CriterionResult(**c) for c in extracted.get("criteria", [])]

        # source_anchor summary: reference to first criterion or "document root"
        source_anchor = criteria_list[0].source_anchor if criteria_list else "document root"

        logger.info(
            "Parsed document for tenant=%s ldcs=%s criteria=%d needs_review=%s",
            request.tenant_id,
            ldcs_detected,
            len(criteria_list),
            needs_human_review,
        )

        return ParseResponse(
            status="completed",
            domains=domains,
            mini_performance_standards=mps_list,
            criteria=criteria_list,
            needs_human_review=needs_human_review,
            ldcs_detected=ldcs_detected,
            confidence_score=confidence_score,
            source_anchor=source_anchor,
            document_url=request.document_url,
            tenant_id=request.tenant_id,
        )

    except Exception as exc:
        logger.exception("Document parsing failed for tenant=%s", request.tenant_id)
        raise HTTPException(status_code=500, detail=str(exc)) from exc


class DocumentParser:
    """
    Programmatic interface to DocumentParser — wraps the /parse endpoint logic
    for use outside of the HTTP layer (e.g. batch processing, tests).

    Architecture reference: modules/mat/02-architecture/system-architecture.md §4
    """

    def parse(self, document_url: str, tenant_id: str) -> dict:
        """
        Parse a document from *document_url* and return structured criteria JSON.

        Parameters
        ----------
        document_url:
            Signed URL of the document to parse (PDF or DOCX).
        tenant_id:
            Tenant scoping key for audit trail and multi-tenancy isolation.

        Returns
        -------
        dict
            Structured result with domains, mini_performance_standards, criteria,
            source_anchor, needs_human_review, ldcs_detected, and confidence_score.
        """
        try:
            document_text, _fmt = _extract_document_text(document_url)
            ldcs_detected = _detect_ldcs_pattern(document_text)
            extracted = _call_gpt4_turbo(document_text)

            confidence_score = float(extracted.get("confidence_score", 0.5))
            needs_human_review = confidence_score < CONFIDENCE_REVIEW_THRESHOLD

            source_anchor = (
                extracted.get("criteria", [{}])[0].get("source_anchor", "document root")
                if extracted.get("criteria")
                else "document root"
            )

            return {
                "status": "completed",
                "domains": extracted.get("domains", []),
                "mini_performance_standards": extracted.get("mini_performance_standards", []),
                "criteria": extracted.get("criteria", []),
                "needs_human_review": needs_human_review,
                "ldcs_detected": ldcs_detected,
                "confidence_score": confidence_score,
                "source_anchor": source_anchor,
                "document_url": document_url,
                "tenant_id": tenant_id,
            }
        except Exception as exc:
            logger.exception("DocumentParser.parse failed for tenant=%s", tenant_id)
            return {
                "status": "failed",
                "error": str(exc),
                "document_url": document_url,
                "tenant_id": tenant_id,
                "needs_human_review": True,
                "source_anchor": "parse_failed",
            }

