"""
services/parsing.py — Document Parsing service (Wave 15 implementation).

Architecture reference: modules/mat/02-architecture/system-architecture.md §4
  "Criteria Parsing Pipeline: CriteriaUpload → invoke-ai-parse-criteria →
   AI Gateway DocumentParser → DB write-back (domains, mini_performance_standards, criteria)"

FRS: FR-005 (criteria parsing pipeline), FR-103 (error surfacing)
Wave: 15 — Post-Delivery Oversight Remediation (T-W15-IMPL-001)
"""

from __future__ import annotations

import io
import json
import logging
import os
import re
import urllib.parse
from typing import Any, TypedDict

import httpx
from PyPDF2 import PdfReader as PdfReader
from docx import Document as DocxDocument
from fastapi import APIRouter, HTTPException
from openai import OpenAI
from pydantic import BaseModel, ConfigDict

logger = logging.getLogger(__name__)

router = APIRouter()

# Trusted Supabase Storage base URL — from env var only, never user-provided
SUPABASE_STORAGE_URL = os.environ.get("SUPABASE_STORAGE_URL", "").rstrip("/")

# ── LDCS document structure constants ──────────────────────────────────────────
# The LDCS (Local Delivery Compliance Standard) uses 26 MPS across multiple domains.
# Criteria are numbered in a hierarchical X.Y.Z pattern.
LDCS_NUMBERED_HIERARCHY_PATTERN = re.compile(r"\b\d+\.\d+(?:\.\d+)?\b")
LDCS_MPS_TOTAL = 26
LDCS_MARKERS = ["LDCS", "Local Delivery Compliance Standard", "mini performance standard"]

GPT_MODEL = "gpt-4.1"
GPT_MODEL_LARGE = "gpt-5.4"     # escalation model for large/complex documents (LDCS, >10 MPS)
GPT_MODEL_PRO = "gpt-5.4-pro"   # highest-effort model for low-confidence or failed parses
LDCS_ESCALATION_THRESHOLD = 10  # escalate to gpt-5.4 if document has more than this many MPS
LDCS_MIN_CRITERIA_EXPECTED = LDCS_MPS_TOTAL  # minimum expected criteria count for a full LDCS document (1 per MPS)
CONFIDENCE_REVIEW_THRESHOLD = 0.75  # flag needs_human_review when below this
MAX_DOCUMENT_CHARS = 400000  # gpt-5.4 supports 1M token window (~4M chars); 400K covers a full 150-page LDCS document


# ── Request / Response models ───────────────────────────────────────────────────

class ParseRequest(BaseModel):
    """
    Request model for the /parse endpoint.

    Security: document_url is a signed Supabase Storage URL generated by the Edge Function.
    The AI Gateway extracts only the path and query components from this URL and combines
    them with the trusted SUPABASE_STORAGE_URL base from the environment (SSRF mitigation).

    user_instructions: optional caller-supplied parsing guidance injected into the user-role
    message (BD-017/BD-018 prompt injection mitigation — never concatenated into system prompt).
    """
    model_config = ConfigDict(extra='ignore')

    document_url: str
    tenant_id: str
    file_path: str | None = None
    user_instructions: str | None = None


class CriterionResult(BaseModel):
    model_config = ConfigDict(extra='ignore')

    mps_number: str
    number: str
    title: str = ""
    description: str = ""
    source_anchor: str = ""
    intent_statement: str = ""
    guidance: str = ""
    maturity_descriptors: list[dict[str, Any]] = []


class MpsResult(BaseModel):
    model_config = ConfigDict(extra='ignore')

    domain_name: str
    name: str
    number: str
    sort_order: int = 0
    level_descriptors: list[dict[str, Any]] = []


class DomainResult(BaseModel):
    model_config = ConfigDict(extra='ignore')

    name: str
    sort_order: int = 0
    level_descriptors: list[dict[str, Any]] = []


class ParseResponse(BaseModel):
    model_config = ConfigDict(extra='ignore')

    status: str
    domains: list[DomainResult]
    mini_performance_standards: list[MpsResult]
    criteria: list[CriterionResult]
    needs_human_review: bool
    ldcs_detected: bool
    confidence_score: float
    source_anchor: str
    document_url: str
    tenant_id: str


# ── Typed AI response shapes (TypedDicts) ────────────────────────────────────────

class ParsedCriterion(TypedDict, total=False):
    mps_number: str
    number: str
    title: str
    description: str
    intent_statement: str
    guidance: str
    source_anchor: str
    maturity_descriptors: list[dict]  # [{"level": int, "descriptor_text": str}]


class ParsedMPS(TypedDict, total=False):
    domain_name: str
    name: str
    number: str
    sort_order: int
    level_descriptors: list[dict]  # [{"level": int, "descriptor_text": str}]


class ParsedDomain(TypedDict, total=False):
    name: str
    sort_order: int
    level_descriptors: list[dict]  # [{"level": int, "descriptor_text": str}]


# ── Text extraction helpers ─────────────────────────────────────────────────────

def _extract_text_from_pdf(content: bytes) -> str:
    """Extract raw text from a PDF document using PyPDF2."""
    reader = PdfReader(io.BytesIO(content))
    pages = []
    for page in reader.pages:
        text = page.extract_text()
        if text:
            pages.append(text)
    return "\n".join(pages)


def _extract_text_from_docx(content: bytes) -> str:
    """Extract raw text from a DOCX document using python-docx."""
    doc = DocxDocument(io.BytesIO(content))
    return "\n".join(para.text for para in doc.paragraphs if para.text.strip())


# SSRF mitigation: only extract path+query from the signed URL and combine
# with the trusted storage base URL from the environment.
# This ensures the scheme and hostname are never user-controlled.
def _build_safe_fetch_url(document_url: str) -> str:
    """
    Build a safe fetch URL by using the trusted SUPABASE_STORAGE_URL base
    and appending only the path and query extracted from the signed URL.

    This prevents SSRF: the scheme and hostname come from a trusted env var,
    not from the user-provided signed URL string.

    Path deduplication: if SUPABASE_STORAGE_URL already contains a path prefix
    (e.g. "/storage/v1") and the signed URL path also starts with that same prefix,
    the prefix is stripped from the signed URL path before concatenation to avoid
    producing a doubled path such as "/storage/v1/storage/v1/...".
    """  
    parsed = urllib.parse.urlparse(document_url)
    # Only use path and query from the signed URL (never scheme or host)
    path = parsed.path.lstrip("/")
    query = f"?{parsed.query}" if parsed.query else ""
    if not SUPABASE_STORAGE_URL:
        raise ValueError("SUPABASE_STORAGE_URL environment variable is not configured")
    base = SUPABASE_STORAGE_URL.rstrip("/")
    # Strip any path prefix that SUPABASE_STORAGE_URL already contains,
    # to prevent duplication (e.g. /storage/v1/storage/v1/...).
    base_path_prefix = urllib.parse.urlparse(base).path.lstrip("/")
    if base_path_prefix and path.startswith(base_path_prefix):
        path = path[len(base_path_prefix):].lstrip("/")
    return f"{base}/{path}{query}"


def _extract_document_text(document_url: str) -> tuple[str, str]:
    """
    Download document from Supabase Storage and extract text.

    SSRF mitigation: scheme and hostname come from SUPABASE_STORAGE_URL (env var),
    not from the user-provided signed URL. Only path and query are extracted from
    the user-provided URL.

    Returns (extracted_text, format) where format is 'pdf' or 'docx'.
    """  
    safe_url = _build_safe_fetch_url(document_url)
    response = httpx.get(safe_url, follow_redirects=False, timeout=30)
    response.raise_for_status()

    content_type = response.headers.get("content-type", "").lower()
    content = response.content

    if "pdf" in content_type or document_url.lower().endswith(".pdf"):
        return _extract_text_from_pdf(content), "pdf"
    elif "wordprocessingml" in content_type or document_url.lower().endswith(".docx"):
        return _extract_text_from_docx(content), "docx"
    else:
        # Attempt PDF first, then DOCX
        try:
            return _extract_text_from_pdf(content), "pdf"
        except Exception:
            return _extract_text_from_docx(content), "docx"


def _detect_ldcs_pattern(text: str) -> bool:
    """Detect whether the document text follows the LDCS numbered hierarchy."""
    has_numbered_hierarchy = bool(LDCS_NUMBERED_HIERARCHY_PATTERN.search(text))
    has_ldcs_marker = any(marker.lower() in text.lower() for marker in LDCS_MARKERS)
    return has_numbered_hierarchy or has_ldcs_marker


# ── GPT structured extraction ───────────────────────────────────────────────────

_SYSTEM_PROMPT = """\
You are Maturion, an expert compliance document analyser.
Your output MUST always be a JSON object matching this exact schema:
{
  "confidence_score": <float 0.0-1.0>,
  "domains": [
    {
      "name": "...",
      "sort_order": <int>,
      "level_descriptors": [
        {"level": 1, "descriptor_text": "..."},
        {"level": 2, "descriptor_text": "..."},
        {"level": 3, "descriptor_text": "..."},
        {"level": 4, "descriptor_text": "..."},
        {"level": 5, "descriptor_text": "..."}
      ]
    }
  ],
  "mini_performance_standards": [
    {
      "domain_name": "...",
      "name": "...",
      "number": "...",
      "sort_order": <int>,
      "level_descriptors": [
        {"level": 1, "descriptor_text": "..."},
        {"level": 2, "descriptor_text": "..."},
        {"level": 3, "descriptor_text": "..."},
        {"level": 4, "descriptor_text": "..."},
        {"level": 5, "descriptor_text": "..."}
      ]
    }
  ],
  "criteria": [
    {
      "mps_number": "...",
      "number": "...",
      "title": "...",
      "description": "...",
      "intent_statement": "...",
      "guidance": "...",
      "source_anchor": "<page or section reference in source document>",
      "maturity_descriptors": [
        {"level": 1, "descriptor_text": "..."},
        {"level": 2, "descriptor_text": "..."},
        {"level": 3, "descriptor_text": "..."},
        {"level": 4, "descriptor_text": "..."},
        {"level": 5, "descriptor_text": "..."}
      ]
    }
  ]
}
Output schema is INVARIANT — it never changes regardless of document type.
CRITICAL RULES:
- NEVER invent, fabricate, or hallucinate criteria. Only extract what is in the document.
- description fields MUST contain the COMPLETE VERBATIM text of each criterion —
  including all intent statements, required actions, sub-items, and bullets, word for word.
  Summarisation is PROHIBITED. This is a legal compliance document.
- title: extract the VERBATIM title or label of the criterion as it appears in the document.
  If no distinct title is present, use the first 5–8 significant words of the description verbatim.
- intent_statement: extract VERBATIM from the document if an explicit intent or purpose
  statement is present. Use empty string "" if no intent statement is present —
  do NOT summarise, paraphrase, or invent.
- guidance: extract VERBATIM implementation guidance text from the document if present
  (distinct from description). Use empty string "" if absent — do NOT invent.
- source_anchor must reference the section or page number in the source document for traceability.
- maturity_descriptors: extract the 5 maturity level descriptions (levels 1-5) VERBATIM
  from the document if explicitly provided. Use empty array [] if not present —
  do NOT infer or fabricate descriptors. Level 1 = initial/ad-hoc, Level 5 = optimised/exemplary.
- level_descriptors in domains and mini_performance_standards follow the same rule:
  extract VERBATIM if present, empty array [] if absent.
- In each criterion, mps_number MUST exactly match the number field of the corresponding
  mini_performance_standard entry — use the exact same string, no reformatting.
The user will tell you how to interpret this specific document's structure.
"""

_CRITERIA_ONLY_SYSTEM_PROMPT = """\
You are Maturion, an expert compliance document analyser.
Your output MUST be a JSON object containing ONLY a "criteria" array:
{
  "criteria": [
    {
      "mps_number": "...",
      "number": "...",
      "title": "...",
      "description": "...",
      "intent_statement": "...",
      "guidance": "...",
      "source_anchor": "<page or section reference in source document>",
      "maturity_descriptors": [
        {"level": 1, "descriptor_text": "..."},
        {"level": 2, "descriptor_text": "..."},
        {"level": 3, "descriptor_text": "..."},
        {"level": 4, "descriptor_text": "..."},
        {"level": 5, "descriptor_text": "..."}
      ]
    }
  ]
}
CRITICAL RULES:
- Extract ONLY the criteria array — do NOT include domains or mini_performance_standards.
- For each MPS number provided in the context, extract ALL criteria that belong to it.
- description fields MUST contain the COMPLETE VERBATIM text of each criterion —
  including all intent statements, required actions, sub-items, and bullets, word for word.
  Summarisation is PROHIBITED. This is a legal compliance document.
- title: extract the VERBATIM title or label of the criterion as it appears in the document.
  If no distinct title is present, use the first 5–8 significant words of the description verbatim.
- mps_number MUST exactly match the number field of the parent MPS from the provided MPS list.
- source_anchor must reference the section or page number in the source document for traceability.
- NEVER invent, fabricate, or hallucinate criteria. Only extract what is in the document.
"""


def _call_gpt(document_text: str, user_instructions: str | None = None, model: str | None = None) -> dict[str, Any]:
    """Call GPT model to extract structured criteria from document text.

    Automatically escalates to GPT_MODEL_LARGE if the response is truncated
    (finish_reason="length") — implementing the AI policy auto-escalation requirement.

    Parameters
    ----------
    document_text:
        Full document text to parse.
    user_instructions:
        Optional caller-supplied guidance injected into the user-role message
        (BD-017/BD-018 prompt injection mitigation).
    model:
        GPT model to use. Defaults to GPT_MODEL. Pass GPT_MODEL_LARGE to force escalation.
    """
    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))
    use_model = model or GPT_MODEL

    # Build user message: inject parsing instructions when provided.
    # Structural separation (BD-017/BD-018): user_instructions are wrapped in XML-like
    # delimiters to create a clear boundary between user-provided instructions and the
    # document text, reducing prompt injection risk.
    if user_instructions:
        user_message = (
            f"<instructions>\n{user_instructions}\n</instructions>\n\n"
            f"<document>\n{document_text[:MAX_DOCUMENT_CHARS]}\n</document>"
        )
    else:
        user_message = (
            f"Extract the criteria hierarchy from this compliance document:"
            f"\n\n{document_text[:MAX_DOCUMENT_CHARS]}"
        )

    # O-series models (o1, o3, o4-mini, etc.) do not accept temperature
    O_SERIES_MODELS = {"o1", "o1-mini", "o1-preview", "o3", "o3-mini", "o4-mini"}
    # gpt-5.4 and gpt-5.4-pro require max_completion_tokens (not max_tokens)
    COMPLETION_TOKENS_MODELS = {GPT_MODEL_LARGE, GPT_MODEL_PRO}
    token_key = "max_completion_tokens" if use_model in COMPLETION_TOKENS_MODELS else "max_tokens"
    extra_kwargs: dict[str, Any] = {token_key: 32000 if use_model in COMPLETION_TOKENS_MODELS else 16000}
    if use_model not in O_SERIES_MODELS:
        extra_kwargs["temperature"] = 0.1

    response = client.chat.completions.create(
        model=use_model,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        response_format={"type": "json_object"},
        **extra_kwargs,
    )

    if response.choices[0].finish_reason == "length":
        if use_model == GPT_MODEL:
            logger.warning(
                "%s response truncated — escalating to %s for document parsing",
                use_model,
                GPT_MODEL_LARGE,
            )
            return _call_gpt(document_text, user_instructions=user_instructions, model=GPT_MODEL_LARGE)
        elif use_model == GPT_MODEL_LARGE:
            logger.warning(
                "%s response truncated — escalating to %s for document parsing",
                use_model,
                GPT_MODEL_PRO,
            )
            return _call_gpt(document_text, user_instructions=user_instructions, model=GPT_MODEL_PRO)
        raise ValueError(
            f"GPT response was truncated using {use_model} (finish_reason=length) — "
            "document requires manual review"
        )

    return json.loads(response.choices[0].message.content or "{}").


def _call_gpt_criteria_only(
    document_text: str,
    mps_list: list[dict[str, Any]],
    user_instructions: str | None = None,
) -> list[dict[str, Any]]:
    """Second-pass GPT call using gpt-5.4 to extract ONLY criteria for an LDCS document.

    Used when the first pass extracted domains and MPS but returned 0 criteria —
    indicating the single-pass approach exhausted the output token budget.
    Provides the already-extracted MPS list as context and asks gpt-5.4 to extract criteria only.

    Parameters
    ----------
    document_text:
        Full document text.
    mps_list:
        List of MPS dicts already extracted in pass 1 (number + name used as context).
    user_instructions:
        Optional caller-supplied guidance forwarded from the original parse request.
    """
    client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

    mps_context = json.dumps(
        [{"number": m.get("number", ""), "name": m.get("name", "")} for m in mps_list],
        indent=2,
    )

    base_message = (
        f"The following MPS (Mini Performance Standards) were already extracted from this document:\n"
        f"{mps_context}\n\n"
        f"Now extract ALL criteria for every MPS listed above from the document below.\n"
        f"For each criterion, set mps_number to exactly match its parent MPS's number field.\n\n"
    )

    if user_instructions:
        user_message = (
            f"<instructions>\n{user_instructions}\n</instructions>\n\n"
            f"{base_message}"
            f"<document>\n{document_text[:MAX_DOCUMENT_CHARS]}\n</document>"
        )
    else:
        user_message = (
            f"{base_message}"
            f"<document>\n{document_text[:MAX_DOCUMENT_CHARS]}\n</document>"
        )

    response = client.chat.completions.create(
        model=GPT_MODEL_LARGE,
        messages=[
            {"role": "system", "content": _CRITERIA_ONLY_SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
        response_format={"type": "json_object"},
        max_completion_tokens=32000,  # gpt-5.4 requires max_completion_tokens, not max_tokens
    )

    if response.choices[0].finish_reason == "length":
        raise ValueError(
            f"GPT response was truncated using {GPT_MODEL_LARGE} in criteria-only extraction "
            "(finish_reason=length) — document exceeds maximum processing capacity"
        )

    result = json.loads(response.choices[0].message.content or "{}")
    return result.get("criteria", [])


# ── FastAPI route ───────────────────────────────────────────────────────────────

@router.post("/parse", response_model=ParseResponse)
async def parse_document(request: ParseRequest) -> ParseResponse:
    """
    Parse a compliance document and return structured Domain → MPS → Criteria hierarchy.

    Security: document_url must be a signed Supabase Storage URL; external URLs are
    rejected by the invoking Edge Function (SSRF mitigation at the Edge Function layer).
    """
    try:
        # 1. Extract document text
        document_text, _doc_format = _extract_document_text(request.document_url)

        # 2. Detect LDCS pattern
        ldcs_detected = _detect_ldcs_pattern(document_text)

        # 3. Call GPT for structured extraction
        # For LDCS documents, use gpt-5.4 directly for pass 1 — gpt-4.1 hits output token limits
        # on large LDCS documents (26 MPS, ~180 criteria) and returns partial results with
        # finish_reason="stop" (not "length"), bypassing the truncation escalation guard.
        if ldcs_detected:
            logger.warning(
                "LDCS document detected — using %s for pass 1 to ensure full extraction",
                GPT_MODEL_LARGE,
            )
            extracted = _call_gpt(document_text, user_instructions=request.user_instructions, model=GPT_MODEL_LARGE)
        else:
            extracted = _call_gpt(document_text, user_instructions=request.user_instructions)

        # 4. Two-pass strategy: if LDCS confirmed but criteria count is below the expected minimum
        # (fewer criteria than MPS — clearly partial extraction), run a second focused pass using
        # gpt-5.4 to extract criteria only.
        if (
            ldcs_detected
            and len(extracted.get("mini_performance_standards", [])) >= LDCS_ESCALATION_THRESHOLD
            and len(extracted.get("criteria", [])) < LDCS_MIN_CRITERIA_EXPECTED
            and len(extracted.get("domains", [])) > 0
        ):
            logger.warning(
                "LDCS document pass 1 returned only %d criteria (expected >= %d) — "
                "running pass 2 with gpt-5.4 for criteria-only extraction",
                len(extracted.get("criteria", [])),
                LDCS_MIN_CRITERIA_EXPECTED,
            )
            extracted["criteria"] = _call_gpt_criteria_only(
                document_text,
                extracted["mini_performance_standards"],
                user_instructions=request.user_instructions,
            )

        confidence_score: float = float(extracted.get("confidence_score", 0.5))
        needs_human_review: bool = confidence_score < CONFIDENCE_REVIEW_THRESHOLD

        # 4. Build typed response
        domains = [DomainResult(**d) for d in extracted.get("domains", [])]
        mps_list = [MpsResult(**m) for m in extracted.get("mini_performance_standards", [])]
        criteria_list = [CriterionResult(**c) for c in extracted.get("criteria", [])]

        # source_anchor summary: reference to first criterion or "document root"
        source_anchor = criteria_list[0].source_anchor if criteria_list else "document root"

        logger.info(
            "Parsed document for tenant=%s ldcs=%s criteria=%d needs_review=%s",
            request.tenant_id,
            ldcs_detected,
            len(criteria_list),
            needs_human_review,
        )

        return ParseResponse(
            status="completed",
            domains=domains,
            mini_performance_standards=mps_list,
            criteria=criteria_list,
            needs_human_review=needs_human_review,
            ldcs_detected=ldcs_detected,
            confidence_score=confidence_score,
            source_anchor=source_anchor,
            document_url=request.document_url,
            tenant_id=request.tenant_id,
        )

    except Exception as exc:
        logger.exception("Document parsing failed for tenant=%s", request.tenant_id)
        raise HTTPException(status_code=500, detail=str(exc)) from exc


class DocumentParser:
    """
    Programmatic interface to DocumentParser — wraps the /parse endpoint logic
    for use outside of the HTTP layer (e.g. batch processing, tests).

    Architecture reference: modules/mat/02-architecture/system-architecture.md §4
    """

    def parse(self, document_url: str, tenant_id: str, user_instructions: str | None = None) -> dict:
        """
        Parse a document from *document_url* and return structured criteria JSON.

        Parameters
        ----------
        document_url:
            Signed URL of the document to parse (PDF or DOCX).
        tenant_id:
            Tenant scoping key for audit trail and multi-tenancy isolation.
        user_instructions:
            Optional caller-supplied guidance for interpreting this document's structure.
            Injected into the user-role message (BD-017/BD-018 prompt injection mitigation —
            never concatenated into the system prompt).

        Returns
        -------
        dict
            Structured result with domains, mini_performance_standards, criteria,
            source_anchor, needs_human_review, ldcs_detected, and confidence_score.
        """
        try:
            document_text, _fmt = _extract_document_text(document_url)
            ldcs_detected = _detect_ldcs_pattern(document_text)

            # For LDCS documents, use gpt-5.4 directly for pass 1
            if ldcs_detected:
                logger.warning(
                    "LDCS document detected — using %s for pass 1 to ensure full extraction",
                    GPT_MODEL_LARGE,
                )
                extracted = _call_gpt(document_text, user_instructions=user_instructions, model=GPT_MODEL_LARGE)
            else:
                extracted = _call_gpt(document_text, user_instructions=user_instructions)

            # Two-pass guard: partial criteria → run criteria-only pass
            if (
                ldcs_detected
                and len(extracted.get("mini_performance_standards", [])) >= LDCS_ESCALATION_THRESHOLD
                and len(extracted.get("criteria", [])) < LDCS_MIN_CRITERIA_EXPECTED
                and len(extracted.get("domains", [])) > 0
            ):
                logger.warning(
                    "LDCS document pass 1 returned only %d criteria (expected >= %d) — "
                    "running pass 2 with gpt-5.4 for criteria-only extraction",
                    len(extracted.get("criteria", [])),
                    LDCS_MIN_CRITERIA_EXPECTED,
                )
                extracted["criteria"] = _call_gpt_criteria_only(
                    document_text,
                    extracted["mini_performance_standards"],
                    user_instructions=user_instructions,
                )

            confidence_score = float(extracted.get("confidence_score", 0.5))
            needs_human_review = confidence_score < CONFIDENCE_REVIEW_THRESHOLD

            source_anchor = (
                extracted.get("criteria", [{}])[0].get("source_anchor", "document root")
                if extracted.get("criteria")
                else "document root"
            )

            return {
                "status": "completed",
                "domains": extracted.get("domains", []),
                "mini_performance_standards": extracted.get("mini_performance_standards", []),
                "criteria": extracted.get("criteria", []),
                "needs_human_review": needs_human_review,
                "ldcs_detected": ldcs_detected,
                "confidence_score": confidence_score,
                "source_anchor": source_anchor,
                "document_url": document_url,
                "tenant_id": tenant_id,
            }
        except Exception as exc:
            logger.exception("DocumentParser.parse failed for tenant=%s", tenant_id)
            return {
                "status": "failed",
                "error": str(exc),
                "document_url": document_url,
                "tenant_id": tenant_id,
                "needs_human_review": True,
                "source_anchor": "parse_failed",
            }